#!/usr/bin/env sh

if ! [ $(id -u) = 0 ]; then
   echo "Error: root privileges are needed to run this script"
   exit 1
fi

APPLESMC="/sys/module/applesmc/drivers/platform:applesmc/applesmc.768/"
SPEED=$1

if [ -z "$SPEED" ]
then
      echo "Please enter a value between 1 - 8000"
else

if [ -d "$APPLESMC" ]; then
      echo $SPEED > /sys/module/applesmc/drivers/platform:applesmc/applesmc.768/fan1_min
else
      echo "Error: ${DIR} not found. Can not continue."
      read -n 1 -s
fi      
fi

