#!/usr/bin/env sh

## QUICK SIMPLE SCRIPT TO CONTROL FAN SPEED WITHOUT HAVING TO TYPE THE ENTIRE CODE EACH TIME ##
## RUNNING FAN AT FULL SPEED FOR LONG TIME WILL DO DAMAGE TO THE FAN ##

#Figlet is required for ascii logo
command -v figlet >/dev/null 2>&1 || { echo >&2 "Figlet is missing. Run sudo apt install figlet to continue....."; exit 1; }

#Clear the screen
clear

#Print ascii logo
figlet -c Applesmc fan controller

#Path to Apple System Management Controller
APPLESMC="/sys/module/applesmc/drivers/platform:applesmc/applesmc.768/"

# If path is found execute code if not print error message
if [ -d "$APPLESMC" ]; then

echo "\nTested on mid 2013 apple macbook pro, might work on some later macbooks.\n"
echo -n "Enter fan speed 1 - 8000: " ; read x
echo $x > /sys/module/applesmc/drivers/platform:applesmc/applesmc.768/fan1_min
clear

else

echo "Error: ${APPLESMC} not found. Can not continue."
read -n 1 -s

fi

